stages:
  - pre-test
  - build
  - test
  - deploy
  - cleanup

variables:
  PYTHON_VERSION: "3.8"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_REPOSITORY: ${DOCKER_REPOSITORY_BASE_URI}/tc-data/airflow
  DOCKER_IMAGE_TAG: gitlab-${CI_PIPELINE_ID}
  APP_NAME: "airflow"

black:
  stage: pre-test
  tags:
    - docker
  image: python:${PYTHON_VERSION}
  script:
    - pip install black
    - black --check .

build_image:
  stage: build
  tags:
    - docker
  services:
    - docker:stable-dind
  image: docker:stable
  script:
    - apk add -U python3 && pip3 install awscli
    - $(aws ecr get-login --no-include-email --region ca-central-1)
    - docker build -t ${DOCKER_REPOSITORY}:${DOCKER_IMAGE_TAG} .
    - docker push ${DOCKER_REPOSITORY}:${DOCKER_IMAGE_TAG}

sast:
  stage: test
  tags:
    - docker
  image: python:${PYTHON_VERSION}
  script:
    - pip install bandit
    - bandit -r .

dependencies_scan:
  stage: test
  tags:
    - docker
  image: python:${PYTHON_VERSION}
  script:
    - pip install pipenv
    - pipenv lock
    - pipenv check

trivy:
  stage: test
  tags:
    - docker
  image: docker:stable
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    IMAGE: trivy-ci-test:$CI_COMMIT_SHA
  before_script:
    - apk add --no-cache curl
    - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - echo $VERSION
    - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
    - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
  allow_failure: true
  script:
    # Build image
    - docker build -t $IMAGE .
    # Build report
    - ./trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@contrib/gitlab.tpl" -o gl-container-scanning-report.json $IMAGE
    # Print report
    - ./trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --severity HIGH $IMAGE
    # Fail on high and critical vulnerabilities
    - ./trivy --exit-code 1 --cache-dir .trivycache/ --severity CRITICAL --no-progress $IMAGE
  cache:
    paths:
      - .trivycache/
  # Enables https://docs.gitlab.com/ee/user/application_security/container_scanning/ (Container Scanning report is available on GitLab EE Ultimate or GitLab.com Gold)
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json

deploy_production:
  stage: deploy
  tags:
    - k8s
  image:
    name: pgag/kubectl-jsonnet
    entrypoint: [""]
  script:
    - |
      jsonnet -J /ksonnet-lib k8s/app.jsonnet \
        -V APP_NAME \
        -V KUBE_NAMESPACE \
        -V DOCKER_REPOSITORY \
        -V DOCKER_IMAGE_TAG \
        -V FERNET_KEY \
        -V WEBSERVER_SECRET_KEY \
        -V AWS_SES_USERNAME \
        -V AWS_SES_PASSWORD \
        -V CI_ENVIRONMENT_SLUG | kubectl --token=${KUBE_TOKEN} apply -f -
  environment:
    name: production
    url: https://airflow.tcdata.co/${CI_ENVIRONMENT_SLUG}
  only:
    - master

deploy_review:
  stage: deploy
  tags:
    - k8s
  image:
    name: pgag/kubectl-jsonnet
    entrypoint: [""]
  script:
    - |
      jsonnet -J /ksonnet-lib k8s/app.jsonnet \
        -V APP_NAME \
        -V KUBE_NAMESPACE \
        -V DOCKER_REPOSITORY \
        -V DOCKER_IMAGE_TAG \
        -V FERNET_KEY \
        -V WEBSERVER_SECRET_KEY \
        -V AWS_SES_USERNAME \
        -V AWS_SES_PASSWORD \
        -V CI_ENVIRONMENT_SLUG | kubectl --token=${KUBE_TOKEN} apply -f -
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://airflow.tcdata.co/${CI_ENVIRONMENT_SLUG}
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: cleanup
  tags:
    - k8s
  variables:
    GIT_STRATEGY: none
  image:
    name: pgag/kubectl-jsonnet
    entrypoint: [""]
  script:
    - |
      kubectl --token=${KUBE_TOKEN} -n ${KUBE_NAMESPACE} \
      delete deploy,service,ingress,secret,postgres,serviceinstance,servicebinding,networkpolicy.crd.projectcalico.org \
      -l app=${APP_NAME},env=${CI_ENVIRONMENT_SLUG}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master
