default:
      image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest #Docker image to use for build jobs

cdk_test:
  stage: test
  before_script:
    - apt-get -qq update
    - pip3 install -r requirements.txt
    - pip3 install black
    - black --check . # python code formatter

  script:
  - cdk doctor #Check your set-up for potential problems
  - cdk synth #Synthesizes and prints the CloudFormation template for this stack
  - cdk diff # Compares the specified stack with the deployed stack or a local template file, and returns with status 1 if any difference is found
  - cdk ls # Lists all stacks in the app
  - cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_DEFAULT_REGION #Deploys the CDK toolkit stack into an AWS environment
