default:
      image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest #Docker image to use for build jobs
cdk_test:
  environment:
    name: development
  stage: test
  script:
  - echo $AWS_ACCESS_KEY_ID
