pipelines:
  default:
    - step:
        name: Build and push docker image
        image: atlassian/pipelines-awscli
        script:
          - $(aws ecr get-login --no-include-email --region ca-central-1)
          - docker build -t ${DOCKER_REPOSITORY}:bitbucket-${BITBUCKET_BUILD_NUMBER} .
          - docker push ${DOCKER_REPOSITORY}:bitbucket-${BITBUCKET_BUILD_NUMBER}
        services:
          - docker
    - step:
        name: Deploy to production
        image: pgag/kubectl-jsonnet
        deployment: production
        script:
          - |
              echo ${KUBE_CA_PEM_BASE64} | base64 -d > .kube-ca.crt && \
              kubectl config set-cluster kubernetes --server=${KUBE_URL} --certificate-authority=.kube-ca.crt && \
              kubectl config set-credentials bitbucket --token=${KUBE_TOKEN} && \
              kubectl config set-context kubernetes --cluster=kubernetes --user=bitbucket --namespace=${KUBE_NAMESPACE} && \
              kubectl config use-context kubernetes
          - |
              jsonnet -J /ksonnet-lib k8s/airflow.jsonnet \
                -V DOCKER_REPOSITORY \
                -V BITBUCKET_BUILD_NUMBER \
                -V WEBSERVER_SECRET_KEY \
                -V BITBUCKET_DEPLOYMENT_ENVIRONMENT \
                -V FERNET_KEY | kubectl apply -f -