dt_comm = {
    "customer_ref_no": str,
    "business_name": str,
    "address": str,
    "city": str,
    "province": str,
    "postal_code": str,
    "telephone": str,
    "fax": str,
    "Match Ref Nbr": str,
    "SEQUENCE NUMBER": str,
    "Match Hit Flag": str,
    "Match Subject Nbr": str,
    "Match Company Nbr": int,
    "Match Company Name": str,
    "Match Company Address": str,
    "Match Company City": str,
    "Match Company Province": str,
    "Match Company Postal Code": str,
    "Match Company Phone": str,
    "Primary Subject Nbr": str,
    "Primary Company Nbr": int,
    "Prim Company Name": str,
    "Prim Company Address": str,
    "Prim Company City": str,
    "Prim Company Province": str,
    "Prim Company Postal Code": str,
    "Prim Company Phone": str,
    "Match Comp Year Estab": str,
    "Match Company SIC Code": str,
    "Match Comp SIC Desc English": str,
    "Match Comp SIC Desc French": str,
    "Match Comp NAICS Code": str,
    "Match Comp NAICS Desc English": str,
    "Match Comp NAICS Desc French": str,
    "Prim Comp Year Estab": str,
    "Prim Company SIC Code": str,
    "Prim SIC Desc English": str,
    "Prim SIC Desc French": str,
    "Prim NAICS Code": str,
    "Prim NAICS Desc English": str,
    "Prim NAICS Desc French": str,
    "CI SCORE": str,
    "PI SCORE": str,
    "CDS Model Number": str,
    "CDS Reject Indicat.": str,
    "CDS Reject Code": str,
    "CDS Score Value": str,
    "CDS Reason Code 1": str,
    "CDS Reason Code 2": str,
    "CDS Reason Code 3": str,
    "CDS Reason Code 4": str,
    "BFRS Model Number": str,
    "BFRS Reject Indicat.": str,
    "BFRS Reject Code": str,
    "BFRS Score Value": str,
    "BFRS Reason Code 1": str,
    "BFRS Reason Code 2": str,
    "BFRS Reason Code 3": str,
    "BFRS Reason Code 4": str,
    "CS Model Number": str,
    "CS Reject Indicat.": str,
    "CS Reject Code": str,
    "CS Score Value": str,
    "CS Reason Code 1": str,
    "CS Reason Code 2": str,
    "CS Reason Code 3": str,
    "CS Reason Code 4": str,
    "NBR OF COLL.": int,
    "AMT OF COLL.": int,
    "NBR OF LGL SUITS": int,
    "AMT OF LGL SUITS": int,
    "NBR OF JUDGMENTS": int,
    "AMT OF JUDGMENTS": int,
    "NBR OF RET. CHQS": int,
    "AMT OF RET. CHQS": int,
    "NBR OF OTHER ITEMS": int,
    "AMT OF OTHER ITEMS": int,
    "90 DAY LINES": int,
    "90 DAY TOTAL_BAL": int,
    "90 DAY HIGH CREDIT": int,
    "90 DAY current": int,
    "90 DAY PD1 ODUE": int,
    "90 DAY PD2 ODUE": int,
    "90 DAY PD3 ODUE": int,
    "90 DAY CREDIT LIMIT": int,
    "90 DAY HIGHEST CREDIT": int,
    "ALL PI SCORE": str,
    "ALL LINES": int,
    "ALL TOTAL BAL": int,
    "ALL HIGH CREDIT": int,
    "ALL CURRENT": int,
    "ALL PD1 ODUE": int,
    "ALL PD2 ODUE": int,
    "ALL PD3 ODUE": int,
    "ALL CREDIT LIMIT": int,
    "ALL HIGHEST CREDIT": int,
    "DATE OF OLDEST LINE": str,
    "DATE OF NEWEST LINE": str,
    "TOTAL# OF COLL.": str,
    "AMT PAID ON COLL.": int,
    "# OF COLL-LAST MTH": int,
    "# OF COLL-LAST 2 MTH": int,
    "# OF COLL-LAST 3 MTH": int,
    "# OF COLL > 3 MTH": int,
    "TREND1 YEAR": int,
    "TREND1 QTR": int,
    "TREND1_#_OF_LINES": int,
    "TREND1_TOTAL_OWING": int,
    "TREND1_CURRENT_DUE": int,
    "TREND1_P1_OVERDUE": int,
    "TREND1_P2_OVERDUE": int,
    "TREND1_P3_OVERDUE": int,
    "TREND2_YEAR": int,
    "TREND2_QTR": int,
    "TREND2_#_OF_LINES": int,
    "TREND2_TOTAL_OWING": int,
    "TREND2_CURRENT_DUE": int,
    "TREND2_P1_OVERDUE": int,
    "TREND2_P2_OVERDUE": int,
    "TREND2_P3_OVERDUE": int,
    "TREND3_YEAR": int,
    "TREND3_QTR": int,
    "TREND3_#_OF_LINES": int,
    "TREND3_TOTAL_OWING": int,
    "TREND3_CURRENT_DUE": int,
    "TREND3_P1_OVERDUE": int,
    "TREND3_P2_OVERDUE": int,
    "trend3_p3_overdue": int,
    "trend4_year": int,
    "trend4_qtr": int,
    "TREND4_#_OF_LINES": int,
    "TREND4_TOTAL_OWING": int,
    "TREND4_CURRENT_DUE": int,
    "TREND4_P1_OVERDUE": int,
    "TREND4_P2_OVERDUE": int,
    "TREND4_P3_OVERDUE": int,
    "TREND5_YEAR": int,
    "TREND5_QTR": int,
    "TREND5_#_OF_LINES": int,
    "TREND5_TOTAL_OWING": int,
    "TREND5_CURRENT_DUE": int,
    "TREND5_P1_OVERDUE": int,
    "TREND5_P2_OVERDUE": int,
    "trend5_p3_overdue": int,
    "TREND6_YEAR": int,
    "TREND6_QTR": int,
    "TREND6_#_OF_LINES": int,
    "TREND6_TOTAL_OWING": int,
    "TREND6_CURRENT_DUE": int,
    "TREND6_P1_OVERDUE": int,
    "TREND6_P2_OVERDUE": int,
    "TREND6_P3_OVERDUE": int,
    "TREND7_YEAR": int,
    "TREND7_QTR": int,
    "TREND7_#_OF_LINES": int,
    "TREND7_TOTAL_OWING": int,
    "TREND7_CURRENT_DUE": int,
    "TREND7_P1_OVERDUE": int,
    "TREND7_P2_OVERDUE": int,
    "TREND7_P3_OVERDUE": int,
    "TREND8_YEAR": int,
    "TREND8_QTR": int,
    "TREND8_#_OF_LINES": int,
    "TREND8_TOTAL_OWING": int,
    "TREND8_CURRENT_DUE": int,
    "TREND8_P1_OVERDUE": int,
    "TREND8_P2_OVERDUE": int,
    "TREND8_P3_OVERDUE": int,
    "TREND9_YEAR": int,
    "TREND9_QTR": int,
    "TREND9_#_OF_LINES": int,
    "TREND9_TOTAL_OWING": int,
    "TREND9_CURRENT_DUE": int,
    "TREND9_P1_OVERDUE": int,
    "TREND9_P2_OVERDUE": int,
    "TREND9_P3_OVERDUE": int,
    "INQUIRY_CNT": int,
    "I001 SIC": str,
    "I001 MBR NAME": str,
    "I002 SIC": str,
    "I002 MBR NAME": str,
    "I003 SIC": str,
    "I003 MBR NAME": str,
    "I004 SIC": str,
    "I004 MBR NAME": str,
    "I005 SIC": str,
    "I005 MBR NAME": str,
    "I006 SIC": str,
    "I006 MBR NAME": str,
    "I007 SIC": str,
    "I007 MBR NAME": str,
    "I008 SIC": str,
    "I008 MBR NAME": str,
    "I009 SIC": str,
    "I009 MBR NAME": str,
    "I010 SIC": str,
    "I010 MBR NAME": str,
    "I011 SIC": str,
    "I011 MBR NAME": str,
    "I012 SIC": str,
    "I012 MBR NAME": str,
    "I013 SIC": str,
    "I013 MBR NAME": str,
    "I014 SIC": str,
    "I014 MBR NAME": str,
    "I015 SIC": str,
    "I015 MBR NAME": str,
    "I016 SIC": str,
    "I016 MBR NAME": str,
    "I017 SIC": str,
    "I017 MBR NAME": str,
    "I018 SIC": str,
    "I018 MBR NAME": str,
    "I019 SIC": str,
    "I019 MBR NAME": str,
    "I020 SIC": str,
    "I020 MBR NAME": str,
    "I021 SIC": str,
    "I021 MBR NAME": str,
    "I022 SIC": str,
    "I022 MBR NAME": str,
    "I023 SIC": str,
    "I023 MBR NAME": str,
    "I024 SIC": str,
    "I024 MBR NAME": str,
    "I025 SIC": str,
    "I025 MBR NAME": str,
    "I026 SIC": str,
    "I026 MBR NAME": str,
    "I027 SIC": str,
    "I027 MBR NAME": str,
    "I028 SIC": str,
    "I028 MBR NAME": str,
    "I029 SIC": str,
    "I029 MBR NAME": str,
    "I030 SIC": str,
    "I030 MBR NAME": str,
    "I031 SIC": str,
    "I031 MBR NAME": str,
    "I032 SIC": str,
    "I032 MBR NAME": str,
    "I033 SIC": str,
    "I033 MBR NAME": str,
    "I034 SIC": str,
    "I034 MBR NAME": str,
    "I035 SIC": str,
    "I035 MBR NAME": str,
    "I036 SIC": str,
    "I036 MBR NAME": str,
    "I037 SIC": str,
    "I037 MBR NAME": str,
    "I038 SIC": str,
    "I038 MBR NAME": str,
    "I039 SIC": str,
    "I039 MBR NAME": str,
    "I040 SIC": str,
    "I040 MBR NAME": str,
    "I041 SIC": str,
    "I041 MBR NAME": str,
    "I042 SIC": str,
    "I042 MBR NAME": str,
    "I043 SIC": str,
    "I043 MBR NAME": str,
    "I044 SIC": str,
    "I044 MBR NAME": str,
    "I045 SIC": str,
    "I045 MBR NAME": str,
    "I046 SIC": str,
    "I046 MBR NAME": str,
    "I047 SIC": str,
    "I047 MBR NAME": str,
    "I048 SIC": str,
    "I048 MBR NAME": str,
    "I049 SIC": str,
    "I049 MBR NAME": str,
    "I050 SIC": str,
    "I050 MBR NAME": str,
}

dt_tcap = {
    "customer_ref_no": str,
    "business_name": str,
    "address": str,
    "city": str,
    "province": str,
    "postal_code": str,
    "telephone": str,
    "fax": str,
    "SEQUENCE NUMBER": int,
    "COMPANY NUMBER": int,
    "EFX Reserve AVRO HitFlag": int,
    "Score Code2": str,
    "Score Description2": str,
    "Score value2": str,
    "Reason Code2 1": str,
    "Reason Code2 1 Desc": str,
    "Reason Code2 2": str,
    "Reason Code2 2 Desc": str,
    "Reason Code2 3": str,
    "Reason Code2 3 Desc": str,
    "Reason Code2 4": str,
    "Reason Code2 4 Desc": str,
    "Reason Code2 5": str,
    "Reason Code2 5 Desc": str,
    "Reject Code2": str,
    "Reject Code Desc2": str,
    "Model Number2": int,
    "Score Code3": str,
    "Score Description3": str,
    "Score value3": str,
    "Reason Code3 1": str,
    "Reason Code3 1 Desc": str,
    "Reason Code3 2": str,
    "Reason Code3 2 Desc": str,
    "Reason Code3 3": str,
    "Reason Code3 3 Desc": str,
    "Reason Code3 4": str,
    "Reason Code3 4 Desc": str,
    "Reason Code3 5": str,
    "Reason Code3 5 Desc": str,
    "Reject Code3": str,
    "Reject Code Desc3": str,
    "Model Number3": int,
}
