sobjects = [
    {"name": "acceptedeventrelation"},
    {"name": "account"},
    {"name": "account_product_eligibility__c"},
    {"name": "accountcleaninfo"},
    {"name": "accountcontactrelation"},
    {"name": "accountcontactrole"},
    {"name": "accountpartner"},
    {"name": "accountteammember"},
    {"name": "actionlinkgrouptemplate"},
    {"name": "actionlinktemplate"},
    {"name": "additionalnumber"},
    {"name": "agentwork"},
    # {"name": "aggregateresult"},
    {"name": "announcement"},
    {"name": "apexclass"},
    {"name": "apexcomponent"},
    {"name": "apexlog"},
    {"name": "apexpage"},
    # {"name": "apexpageinfo"},
    {"name": "apextestqueueitem"},
    {"name": "apextestresult"},
    {"name": "apextestresultlimits"},
    {"name": "apextestrunresult"},
    {"name": "apextestsuite"},
    {"name": "apextrigger"},
    # {"name": "appdefinition"},
    {"name": "applicationcheck__c"},
    {"name": "appmenuitem"},
    {"name": "appraisal__c"},
    {"name": "approval__c"},
    # {"name": "apptabmember"},
    {"name": "asset"},
    {"name": "assetrelationship"},
    # {"name": "assettokenevent"},
    {"name": "assignment__c"},
    {"name": "assignmentrule"},
    # {"name": "asyncapexjob"},
    # {"name": "attachedcontentdocument"},
    {"name": "auradefinition"},
    {"name": "auradefinitionbundle"},
    # {"name": "auradefinitionbundleinfo"},
    # {"name": "auradefinitioninfo"},
    {"name": "authconfig"},
    {"name": "authconfigproviders"},
    # {"name": "authsession"},
    {"name": "backgroundoperation"},
    # {"name": "backgroundoperationresult"},
    {"name": "brandingset"},
    {"name": "brandingsetproperty"},
    {"name": "brandtemplate"},
    # {"name": "businesshours"},
    {"name": "businessprocess"},
    {"name": "callcenter"},
    {"name": "campaign"},
    # {"name": "campaign_promotions__mdt"},
    {"name": "campaignmember"},
    {"name": "campaignmemberstatus"},
    {"name": "case"},
    {"name": "casearticle"},
    {"name": "casecomment"},
    {"name": "casecontactrole"},
    {"name": "caseexternaldocument"},
    {"name": "casesolution"},
    {"name": "casestatus"},
    {"name": "casesubjectparticle"},
    {"name": "caseteammember"},
    {"name": "caseteamrole"},
    {"name": "caseteamtemplate"},
    {"name": "caseteamtemplatemember"},
    {"name": "caseteamtemplaterecord"},
    {"name": "categorynode"},
    {"name": "categorynodelocalization"},
    {"name": "changelock__c"},
    {"name": "chatter_delete_settings__c"},
    {"name": "chatteractivity"},
    {"name": "chatterextension"},
    {"name": "chatterextensionconfig"},
    {"name": "chatterextensionlocalization"},
    {"name": "checklist_criteria__c"},
    {"name": "checklist_item__c"},
    {"name": "checklist_template__c"},
    # {"name": "clientbrowser"},
    {"name": "collaborationgroup"},
    {"name": "collaborationgroupmember"},
    {"name": "collaborationgroupmemberrequest"},
    {"name": "collaborationgrouprecord"},
    {"name": "collaborationinvitation"},
    # {"name": "colordefinition"},
    {"name": "communication_consent__c"},
    {"name": "community"},
    # {"name": "connectedapplication"},
    {"name": "contact"},
    {"name": "contactcleaninfo"},
    {"name": "contactrequest"},
    {"name": "contentasset"},
    # {"name": "contentbody"},
    {"name": "contentdistribution"},
    {"name": "contentdistributionview"},
    {"name": "contentdocument"},
    # {"name": "contentdocumentlink"},
    {"name": "contentfolder"},
    # {"name": "contentfolderitem"},
    # {"name": "contentfolderlink"},
    # {"name": "contentfoldermember"},
    # {"name": "contenthubitem"},
    {"name": "contenthubrepository"},
    {"name": "contentversion"},
    {"name": "contentworkspace"},
    {"name": "contentworkspacedoc"},
    # {"name": "contentworkspacemember"},
    {"name": "contentworkspacepermission"},
    {"name": "contract"},
    {"name": "contractcontactrole"},
    {"name": "contractstatus"},
    # {"name": "credit_bureau_settings__mdt"},
    {"name": "credit_check__c"},
    # {"name": "cronjobdetail"},
    # {"name": "crontrigger"},
    # {"name": "custombrand"},
    # {"name": "custombrandasset"},
    {"name": "customhttpheader"},
    {"name": "customobjectuserlicensemetrics"},
    {"name": "custompermission"},
    {"name": "custompermissiondependency"},
    {"name": "dashboard"},
    # {"name": "dashboardcomponent"},
    # {"name": "data_sync_field_mapping_setting__mdt"},
    # {"name": "datacloudaddress"},
    # {"name": "datacloudcompany"},
    # {"name": "datacloudcontact"},
    {"name": "datacloudownedentity"},
    {"name": "datacloudpurchaseusage"},
    {"name": "dataintegrationrecordpurchasepermission"},
    {"name": "datasetexport"},
    # {"name": "datasetexportevent"},
    {"name": "datasetexportpart"},
    # {"name": "datastatistics"},
    # {"name": "datatype"},
    {"name": "declinedeventrelation"},
    # {"name": "delayed_days_mapping__mdt"},
    {"name": "document"},
    {"name": "document__c"},
    # {"name": "documentattachmentmap"},
    # {"name": "docusign_document_options__mdt"},
    {"name": "domain"},
    {"name": "domainsite"},
    {"name": "dsfs__docusign_envelope__c"},
    {"name": "dsfs__docusign_envelope_document__c"},
    {"name": "dsfs__docusign_envelope_recipient__c"},
    {"name": "dsfs__docusign_recipient_status__c"},
    {"name": "dsfs__docusign_status__c"},
    {"name": "dsfs__docusignaccountconfiguration__c"},
    {"name": "duplicatejob"},
    {"name": "duplicatejobdefinition"},
    {"name": "duplicatejobmatchingrule"},
    {"name": "duplicatejobmatchingruledefinition"},
    {"name": "duplicaterecorditem"},
    {"name": "duplicaterecordset"},
    {"name": "duplicaterule"},
    {"name": "emailmessage"},
    {"name": "emailmessagerelation"},
    {"name": "emailservicesaddress"},
    {"name": "emailservicesfunction"},
    # {"name": "emailstatus"},
    {"name": "emailtemplate"},
    # {"name": "embeddedservicedetail"},
    # {"name": "entitydefinition"},
    # {"name": "entityparticle"},
    # {"name": "entitysubscription"},
    {"name": "event"},
    # {"name": "eventbussubscriber"},
    {"name": "eventlogfile"},
    {"name": "eventrelation"},
    {"name": "externaldatasource"},
    {"name": "externaldatauserauth"},
    {"name": "externalsocialaccount"},
    {"name": "fairwarn__alert__c"},
    {"name": "fairwarn__alertticketassociation__c"},
    {"name": "fairwarn__investigation__c"},
    {"name": "fairwarn__involved_user__c"},
    # {"name": "fielddefinition"},
    {"name": "fieldpermissions"},
    {"name": "filesearchactivity"},
    {"name": "financial_account__c"},
    {"name": "fiscalyearsettings"},
    # {"name": "flexqueueitem"},
    {"name": "flowinterview"},
    {"name": "flowrecordrelation"},
    {"name": "flowstagerelation"},
    {"name": "folder"},
    # {"name": "folderedcontentdocument"},
    {"name": "footprint__all_reports__c"},
    {"name": "footprint__analysis_log__c"},
    # {"name": "footprint__batch_parameter__mdt"},
    {"name": "footprint__foot_print_recordtype__c"},
    {"name": "footprint__footprint__c"},
    {"name": "footprint__footprint_allfields__c"},
    {"name": "footprint__footprint_allfu__c"},
    {"name": "footprint__footprint_allobjects__c"},
    {"name": "footprint__footprint_allwf__c"},
    # {"name": "footprint__footprint_line_item__c"},
    # {"name": "footprint__footprint_line_item_detail__c"},
    {"name": "footprint__footprint_listview__c"},
    {"name": "grantedbylicense"},
    # {"name": "group"},
    {"name": "groupmember"},
    {"name": "holiday"},
    # {"name": "icondefinition"},
    {"name": "idea"},
    # {"name": "ideacomment"},
    {"name": "individual"},
    {"name": "industry_id__c"},
    {"name": "installedmobileapp"},
    {"name": "integration_error__c"},
    {"name": "knowledge__datacategoryselection"},
    {"name": "knowledge__ka"},
    {"name": "knowledge__kav"},
    # {"name": "knowledge__viewstat"},
    # {"name": "knowledge__votestat"},
    {"name": "knowledgeableuser"},
    {"name": "knowledgearticle"},
    {"name": "knowledgearticleversion"},
    # {"name": "knowledgearticleviewstat"},
    # {"name": "knowledgearticlevotestat"},
    {"name": "lead"},
    # {"name": "lead_conversion_setting__mdt"},
    {"name": "leadcleaninfo"},
    {"name": "leadstatus"},
    {"name": "lightningexperiencetheme"},
    {"name": "lightningtogglemetrics"},
    {"name": "lightningusagebyapptypemetrics"},
    {"name": "lightningusagebybrowsermetrics"},
    {"name": "lightningusagebyflexipagemetrics"},
    {"name": "lightningusagebypagemetrics"},
    {"name": "linkedarticle"},
    {"name": "listemail"},
    {"name": "listemailrecipientsource"},
    {"name": "listview"},
    {"name": "listviewchart"},
    # {"name": "listviewchartinstance"},
    {"name": "loan__c"},
    # {"name": "loginevent"},
    # {"name": "loginip"},
    # {"name": "logouteventstream"},
    # {"name": "lookedupfromactivity"},
    {"name": "macro"},
    {"name": "macroinstruction"},
    {"name": "mailmergetemplate"},
    {"name": "matchingrule"},
    {"name": "matchingruleitem"},
    {"name": "messagebrokersetting__c"},
    {"name": "milestone__c"},
    # {"name": "milestones_creation_setting__mdt"},
    # {"name": "mobileapplicationdetail"},
    # {"name": "name"},
    {"name": "namedcredential"},
    {"name": "note"},
    {"name": "note__c"},
    # {"name": "oauthtoken"},
    {"name": "objectpermissions"},
    # {"name": "openactivity"},
    {"name": "opportunity"},
    {"name": "opportunityhistory"},
    {"name": "opportunityfieldhistory"},
    {"name": "opportunity__hd"},
    {"name": "opportunity_contact_role__c"},
    # {"name": "opportunity_record_type_setting__mdt"},
    {"name": "opportunitycompetitor"},
    {"name": "opportunitycontactrole"},
    {"name": "opportunitylineitem"},
    {"name": "opportunitypartner"},
    {"name": "opportunitystage"},
    {"name": "opportunityteammember"},
    {"name": "order"},
    {"name": "orderitem"},
    # {"name": "organization"},
    # {"name": "orglifecyclenotification"},
    {"name": "orgwideemailaddress"},
    # {"name": "outgoingemail"},
    # {"name": "outgoingemailrelation"},
    # {"name": "ownedcontentdocument"},
    # {"name": "ownerchangeoptioninfo"},
    {"name": "partner"},
    {"name": "partner_id__c"},
    {"name": "partnerrole"},
    {"name": "payout__c"},
    {"name": "pendingservicerouting"},
    {"name": "period"},
    # {"name": "permissionset"},
    # {"name": "permissionsetassignment"},
    {"name": "permissionsetgroup"},
    {"name": "permissionsetgroupcomponent"},
    {"name": "permissionsetlicense"},
    {"name": "permissionsetlicenseassign"},
    {"name": "pi__asyncrequest__c"},
    {"name": "pi__asyncrequest_settings__c"},
    {"name": "pi__category_contact_score__c"},
    {"name": "pi__category_lead_score__c"},
    {"name": "pi__demo_settings__c"},
    {"name": "pi__engagecampaignrecipient__c"},
    {"name": "pi__ldfilter__c"},
    {"name": "pi__objectchangelog__c"},
    {"name": "pi__pardot_scoring_category__c"},
    {"name": "pi__pardottask__c"},
    {"name": "pi__partner_settings__c"},
    {"name": "pi__trigger_settings__c"},
    # {"name": "picklistvalueinfo"},
    # {"name": "platformaction"},
    {"name": "platformcachepartition"},
    {"name": "platformcachepartitiontype"},
    {"name": "presenceconfigdeclinereason"},
    {"name": "presencedeclinereason"},
    {"name": "presenceuserconfig"},
    {"name": "presenceuserconfigprofile"},
    {"name": "presenceuserconfiguser"},
    {"name": "pricebook2"},
    {"name": "pricebookentry"},
    {"name": "processdefinition"},
    {"name": "processinstance"},
    {"name": "processinstancenode"},
    {"name": "processinstancestep"},
    {"name": "processinstanceworkitem"},
    {"name": "processnode"},
    {"name": "processor_id__c"},
    {"name": "product2"},
    {"name": "product__c"},
    {"name": "product_summary__c"},
    {"name": "profile"},
    # {"name": "publisher"},
    {"name": "pushtopic"},
    {"name": "queueroutingconfig"},
    {"name": "queuesobject"},
    {"name": "quicktext"},
    {"name": "quote"},
    {"name": "quote__c"},
    {"name": "quote__c_hd"},
    {"name": "quotedocument"},
    {"name": "quotelineitem"},
    # {"name": "quotetemplaterichtextdata"},
    # {"name": "recentlyviewed"},
    {"name": "recordaction"},
    {"name": "recordtype"},
    {"name": "recordtypelocalization"},
    {"name": "reference_data__c"},
    {"name": "registration__c"},
    # {"name": "relationshipdomain"},
    # {"name": "relationshipinfo"},
    {"name": "remuneration__c"},
    {"name": "report"},
    {"name": "samlssoconfig"},
    {"name": "scontrol"},
    {"name": "scontrollocalization"},
    {"name": "searchactivity"},
    # {"name": "searchlayout"},
    {"name": "secureagentscluster"},
    {"name": "servicechannel"},
    {"name": "servicechannelstatus"},
    {"name": "servicepresencestatus"},
    {"name": "sessionpermsetactivation"},
    # {"name": "setupaudittrail"},
    {"name": "setupentityaccess"},
    {"name": "site"},
    # {"name": "sitedetail"},
    {"name": "socialpersona"},
    {"name": "socialpost"},
    {"name": "solution"},
    {"name": "solutionstatus"},
    {"name": "stamp"},
    {"name": "stampassignment"},
    {"name": "stamplocalization"},
    {"name": "staticresource"},
    {"name": "store_code__c"},
    {"name": "streamingchannel"},
    {"name": "subindustry_id__c"},
    # {"name": "system_defaults__mdt"},
    # {"name": "tabdefinition"},
    {"name": "talkdesk__cxmflow__c"},
    {"name": "talkdesk__talkdesk_activity__c"},
    {"name": "talkdesk__talkdesk_disposition_code__c"},
    {"name": "talkdesk__talkdesk_public__c"},
    {"name": "talkdesk__talkdesk_syncing_custom_object__c"},
    {"name": "task"},
    {"name": "taskpriority"},
    {"name": "taskstatus"},
    {"name": "tenantusageentitlement"},
    {"name": "testsuitemembership"},
    # {"name": "thirdpartyaccountlink"},
    {"name": "todaygoal"},
    {"name": "topic"},
    {"name": "topicassignment"},
    {"name": "topiclocalization"},
    # {"name": "trigger_setting__mdt"},
    {"name": "undecidedeventrelation"},
    {"name": "user"},
    {"name": "useraccountteammember"},
    {"name": "userappinfo"},
    {"name": "userappmenucustomization"},
    # {"name": "userappmenuitem"},
    # {"name": "userentityaccess"},
    # {"name": "userfieldaccess"},
    {"name": "userlicense"},
    {"name": "userlistview"},
    {"name": "userlistviewcriterion"},
    # {"name": "userlogin"},
    # {"name": "userpermissionaccess"},
    {"name": "userpreference"},
    # {"name": "userrecordaccess"},
    {"name": "userrole"},
    {"name": "userservicepresence"},
    {"name": "userteammember"},
    {"name": "verification__c"},
    # {"name": "visibilityupdateevent"},
    # {"name": "vote"},
    {"name": "waveautoinstallrequest"},
    {"name": "wavecompatibilitycheckitem"},
    {"name": "web_service_security__c"},
    # {"name": "web_service_settings__c"},
    # {"name": "work_case_creation_settings__mdt"},
]
