from sqlalchemy import text, DATE, column, cast
from sqlalchemy.sql import Select

from salesforce_import_extras.formatters import format_wide_table_select

sobjects = [
    {"name": "aa_element_for_deployment__c"},
    {"name": "aaa_random__c"},
    {"name": "acceptedeventrelation"},
    {
        "name": "account",
        "selectable": {
            "callable": format_wide_table_select,
            "kwargs": {"condition": text("test_account__c = false")},
        },
    },
    {"name": "account_balance__c"},
    {"name": "account_sales_note__c"},
    {"name": "account_score__c"},
    {"name": "account_snapshot__c"},
    {"name": "account_snapshot_daily__c"},
    {"name": "account_snapshot_speed__c"},
    {"name": "account_statistics__c"},
    {"name": "account_status__c"},
    {"name": "account_status_time_entry__c"},
    {"name": "account_summary__c"},
    {"name": "accountbrand"},
    {"name": "accountcontactrole"},
    {"name": "accountml__c"},
    {"name": "accountpartner"},
    {"name": "accountteammember"},
    {"name": "action_item__c"},
    {"name": "actionlinkgrouptemplate"},
    {"name": "actionlinktemplate"},
    {"name": "activescratchorg"},
    {"name": "acton__accountinfo__c"},
    {"name": "added_to_csa_queue__c"},
    {"name": "additional_payments__c"},
    {"name": "additionalnumber"},
    {"name": "adfa_vs_total_portfolio_snapsho__c"},
    # {"name": "adminsetupevent"},
    {"name": "advance_size_seasonality_multiple__c"},
    {"name": "agenda_item__c"},
    {"name": "agent_code__c"},
    # {"name": "aggregateresult"},
    {"name": "agreementwebapp__c"},
    {"name": "alberta_portfolio_analytic_snapshot__c"},
    {"name": "amazon_s3_settings__c"},
    {"name": "amount_to_writeoff_with_reversals__c"},
    {"name": "amount_withheld_red_flag_bg__c"},
    {"name": "analytic_snapshot_portfolio_by_account__c"},
    {"name": "announcement"},
    {"name": "anticipated_attrition_snapshot__c"},
    {"name": "apexclass"},
    {"name": "apexcomponent"},
    {"name": "apexlog"},
    {"name": "apexpage"},
    # {"name": "apexpageinfo"},
    {"name": "apextestqueueitem"},
    {"name": "apextestresult"},
    {"name": "apextestresultlimits"},
    {"name": "apextestrunresult"},
    {"name": "apextestsuite"},
    {"name": "apextrigger"},
    # {"name": "apievent"},
    # {"name": "apieventstream"},
    # {"name": "appdefinition"},
    {"name": "applicant__c"},
    {"name": "applicant_grading__c"},
    {"name": "application__c"},
    {"name": "appmenuitem"},
    {"name": "approval"},
    # {"name": "apptabmember"},
    {"name": "apxt_cmqr__conga_merge_query__c"},
    {"name": "apxtconga4__conga_composer_settings__c"},
    {"name": "apxtconga4__conga_email_staging__c"},
    {"name": "apxtconga4__conga_email_template__c"},
    {"name": "apxtconga4__conga_template__c"},
    {"name": "area_code__c"},
    {"name": "asset"},
    {"name": "assetrelationship"},
    # {"name": "assettokenevent"},
    {"name": "assigning_flag__c"},
    {"name": "assignmentrule"},
    # {"name": "asyncapexjob"},
    {"name": "asynchronous_apex_error__c"},
    # {"name": "attachedcontentdocument"},
    # {"name": "attachedcontentnote"},
    {"name": "auradefinition"},
    # {"name": "auradefinitionbundle"},
    # {"name": "auradefinitionbundleinfo"},
    # {"name": "auradefinitioninfo"},
    {"name": "authconfig"},
    {"name": "authconfigproviders"},
    # {"name": "authsession"},
    {"name": "auto_snapshot__c"},
    {"name": "backgroundoperation"},
    # {"name": "backgroundoperationresult"},
    {"name": "bad_debts_factor__c"},
    {"name": "bad_debts_snapshot__c"},
    {"name": "bank_balance_snapshot__c"},
    {"name": "bank_statistics__c"},
    {"name": "base_case_rate__c"},
    {"name": "batch_report_emails__c"},
    {"name": "batch_rule__c"},
    {"name": "batchposting__c"},
    {"name": "beacon_statistics__c"},
    {"name": "blnd_dfcs_carousel__c"},
    {"name": "blnd_dfcs_slide__c"},
    {"name": "blnd_dfff_form__c"},
    {"name": "blnd_dfff_page__c"},
    {"name": "blog_a_en__c"},
    {"name": "bmo_zero_balance__c"},
    {"name": "bmo_zero_balance_load__c"},
    {"name": "bookmark"},
    {"name": "brandingset"},
    {"name": "brandingsetproperty"},
    {"name": "brandtemplate"},
    {"name": "budget__c"},
    {"name": "bug__c"},
    {"name": "business_days__c"},
    # {"name": "businesshours"},
    {"name": "businessprocess"},
    {"name": "buyback__c"},
    {"name": "c2g__accountingsummarization2__c"},
    {"name": "c2g__accountingsummarization__c"},
    {"name": "c2g__accountsettings__c"},
    {"name": "c2g__accounttypesettings__c"},
    {"name": "c2g__allocationfilter__c"},
    {"name": "c2g__allocationfilterstructure__c"},
    {"name": "c2g__allocationschedule__c"},
    {"name": "c2g__allocationschedulecompany__c"},
    {"name": "c2g__allocationschedulelog__c"},
    {"name": "c2g__allocationscheduletemplate__c"},
    {"name": "c2g__allocationsplittemplate__c"},
    {"name": "c2g__allocationtemplate__c"},
    {"name": "c2g__allocschedule__c"},
    {"name": "c2g__allocschedulecompany__c"},
    {"name": "c2g__allocschedulelog__c"},
    {"name": "c2g__allocschedulerun__c"},
    {"name": "c2g__allocscheduleruntransaction__c"},
    {"name": "c2g__allocscheduletemplate__c"},
    {"name": "c2g__asofaging__c"},
    {"name": "c2g__asofagingprocesslog__c"},
    {"name": "c2g__asofagingreportsettings__c"},
    {"name": "c2g__asofagingsettings__c"},
    {"name": "c2g__availablesummarizationobject__c"},
    {"name": "c2g__billingsettings__c"},
    {"name": "c2g__budgetsandbalancessettings__c"},
    {"name": "c2g__cancelpayment__c"},
    {"name": "c2g__cancelpaymentlog__c"},
    {"name": "c2g__chartofaccountsmapping__c"},
    {"name": "c2g__chartofaccountsstructure__c"},
    {"name": "c2g__codaaccountingcurrency__c"},
    {"name": "c2g__codaaccountingsettings__c"},
    {"name": "c2g__codaaccountinuse__c"},
    {"name": "c2g__codaagedanalysisdef__c"},
    {"name": "c2g__codabalanceupdateresult__c"},
    {"name": "c2g__codabankaccount__c"},
    {"name": "c2g__codabankreconciliation__c"},
    {"name": "c2g__codabankreconciliationcharge__c"},
    {"name": "c2g__codabankreconciliationlineitem__c"},
    {"name": "c2g__codabankstatement__c"},
    {"name": "c2g__codabankstatementdefinition__c"},
    {"name": "c2g__codabankstatementlineitem__c"},
    {"name": "c2g__codabatchcontrol__c"},
    {"name": "c2g__codabatchcontroldetail__c"},
    {"name": "c2g__codabudget__c"},
    {"name": "c2g__codacashentry__c"},
    {"name": "c2g__codacashentrylineitem__c"},
    {"name": "c2g__codacashmatchinghistory__c"},
    {"name": "c2g__codacashmatchingsettings__c"},
    {"name": "c2g__codachecknumber__c"},
    {"name": "c2g__codacheckrange__c"},
    {"name": "c2g__codacolumnproperty__c"},
    {"name": "c2g__codacompany__c"},
    {"name": "c2g__codacreditnote__c"},
    {"name": "c2g__codacreditnotelineitem__c"},
    {"name": "c2g__codacurrencyrevalbatch__c"},
    {"name": "c2g__codacurrencyrevalbatchlineitem__c"},
    {"name": "c2g__codacurrencyrevaluation__c"},
    {"name": "c2g__codacurrencyrevaluationglaitem__c"},
    {"name": "c2g__codacurrencyrevaluationgroup__c"},
    {"name": "c2g__codacurrencyrevaluationlineitem__c"},
    {"name": "c2g__codacurrencyrevaluationsummary__c"},
    {"name": "c2g__codadataproperty__c"},
    {"name": "c2g__codadimension1__c"},
    {"name": "c2g__codadimension2__c"},
    {"name": "c2g__codadimension3__c"},
    {"name": "c2g__codadimension4__c"},
    {"name": "c2g__codaeventlog__c"},
    {"name": "c2g__codaexchangerate__c"},
    {"name": "c2g__codafinancecorrespondence__c"},
    {"name": "c2g__codaformatdata__c"},
    {"name": "c2g__codageneralledgeraccount__c"},
    {"name": "c2g__codagroupingreference__c"},
    {"name": "c2g__codaincomescheduledefinition__c"},
    {"name": "c2g__codaincschedulestagingjnl__c"},
    {"name": "c2g__codaincschedulestagingjnllineitem__c"},
    {"name": "c2g__codaintegrationrule__c"},
    {"name": "c2g__codaintegrationrulelineitem__c"},
    {"name": "c2g__codaintercompanydefinition__c"},
    {"name": "c2g__codaintercompanytransfer__c"},
    {"name": "c2g__codaintercompanytransferlineitem__c"},
    {"name": "c2g__codaintersectdefinition__c"},
    {"name": "c2g__codainvoice__c"},
    {"name": "c2g__codainvoiceinstallmentlineitem__c"},
    {"name": "c2g__codainvoicelineitem__c"},
    {"name": "c2g__codaitem__c"},
    {"name": "c2g__codajournal__c"},
    {"name": "c2g__codajournallineitem__c"},
    {"name": "c2g__codalookup__c"},
    {"name": "c2g__codamappingformat__c"},
    {"name": "c2g__codamassemailaccount__c"},
    {"name": "c2g__codamassemailaccountlineitem__c"},
    {"name": "c2g__codamatchingreference__c"},
    {"name": "c2g__codaobjectfield__c"},
    {"name": "c2g__codapagenumproperty__c"},
    {"name": "c2g__codapayment__c"},
    {"name": "c2g__codapaymentaccountlineitem__c"},
    {"name": "c2g__codapaymentaccountselection__c"},
    {"name": "c2g__codapaymentbatch__c"},
    {"name": "c2g__codapaymentbatchlineitem__c"},
    {"name": "c2g__codapaymenthistory__c"},
    {"name": "c2g__codapaymentlineitem__c"},
    {"name": "c2g__codapaymentmediacontrol__c"},
    {"name": "c2g__codapaymentmediadetail__c"},
    {"name": "c2g__codapaymentmediasummary__c"},
    {"name": "c2g__codapaymentsettings__c"},
    {"name": "c2g__codapaymenttemplate__c"},
    {"name": "c2g__codapaymenttemplatelineitem__c"},
    {"name": "c2g__codaperiod__c"},
    {"name": "c2g__codaprintformat__c"},
    {"name": "c2g__codaproductinuse__c"},
    {"name": "c2g__codapurchasecreditnote__c"},
    {"name": "c2g__codapurchasecreditnoteexplineitem__c"},
    {"name": "c2g__codapurchasecreditnotelineitem__c"},
    {"name": "c2g__codapurchaseinvoice__c"},
    {"name": "c2g__codapurchaseinvoiceexpenselineitem__c"},
    {"name": "c2g__codapurchaseinvoicelineitem__c"},
    {"name": "c2g__codarecordlock__c"},
    {"name": "c2g__codarecordlockgroup__c"},
    {"name": "c2g__codaschedulelineitem__c"},
    {"name": "c2g__codasection__c"},
    {"name": "c2g__codaselection__c"},
    {"name": "c2g__codaselectioncriterion__c"},
    {"name": "c2g__codasinglemapping__c"},
    {"name": "c2g__codasortorder__c"},
    {"name": "c2g__codatableproperty__c"},
    {"name": "c2g__codataxcode__c"},
    {"name": "c2g__codataxrate__c"},
    {"name": "c2g__codatextdefinition__c"},
    {"name": "c2g__codatransaction__c"},
    {"name": "c2g__codatransactionlineitem__c"},
    {"name": "c2g__codausercompany__c"},
    {"name": "c2g__codavoidpaymentcriteria__c"},
    {"name": "c2g__codayear__c"},
    {"name": "c2g__codayearendlog__c"},
    {"name": "c2g__commonname__c"},
    {"name": "c2g__companyownership__c"},
    {"name": "c2g__currencyrevaluationtemplate__c"},
    {"name": "c2g__currencyrevaluationtemplatelineitem__c"},
    {"name": "c2g__customformassignment__c"},
    {"name": "c2g__customformlayout__c"},
    {"name": "c2g__customformlayoutfield__c"},
    {"name": "c2g__customformlayoutrelatedlist__c"},
    {"name": "c2g__customformlayoutsection__c"},
    {"name": "c2g__dataview__c"},
    {"name": "c2g__dataviewaction__c"},
    {"name": "c2g__dataviewfield__c"},
    {"name": "c2g__dataviewjoin__c"},
    {"name": "c2g__dataviewjoinfilter__c"},
    {"name": "c2g__dataviewtransposeitem__c"},
    {"name": "c2g__fflib_batchprocess__c"},
    {"name": "c2g__fflib_batchprocessdetail__c"},
    {"name": "c2g__fflib_schedulerconfiguration__c"},
    {"name": "c2g__filter__c"},
    {"name": "c2g__filterelement__c"},
    {"name": "c2g__inquirytemplate__c"},
    {"name": "c2g__inquirytemplatecolumn__c"},
    {"name": "c2g__inquirytemplatecolumnfilter__c"},
    {"name": "c2g__inquirytemplatecolumnformula__c"},
    {"name": "c2g__inquirytemplatecommonname__c"},
    {"name": "c2g__inquirytemplateexcludedaction__c"},
    {"name": "c2g__inquirytemplatefilter__c"},
    {"name": "c2g__inquirytemplatercp__c"},
    {"name": "c2g__inquirytemplatesignfilter__c"},
    {"name": "c2g__inquirytemplatesortitem__c"},
    {"name": "c2g__inquirytemplatetransposedrill__c"},
    {"name": "c2g__integrationrulessettings__c"},
    {"name": "c2g__intercompanysettings__c"},
    {"name": "c2g__massdeletebatchlog__c"},
    {"name": "c2g__massdeletecontrolrecord__c"},
    {"name": "c2g__objecttoobjectmap__c"},
    {"name": "c2g__objecttoobjectmapfieldlink__c"},
    {"name": "c2g__onlineinquiriespersonalsetting__c"},
    {"name": "c2g__palettesection__c"},
    {"name": "c2g__postinstallupgradesettings__c"},
    {"name": "c2g__rcppeer__c"},
    {"name": "c2g__relatedcontentpane__c"},
    {"name": "c2g__relatedcontentpanecomponent__c"},
    {"name": "c2g__relatedcontentpanetab__c"},
    {"name": "c2g__reportingbalance__c"},
    {"name": "c2g__summarizationlog__c"},
    {"name": "c2g__summarizationruninformation__c"},
    {"name": "c2g__summarizationtemplate__c"},
    {"name": "c2g__summarizationtemplatefieldprocess__c"},
    {"name": "c2g__taxdetailpayablecreditnote__c"},
    {"name": "c2g__taxdetailpayablecreditnoteexpense__c"},
    {"name": "c2g__taxdetailpayableinvoice__c"},
    {"name": "c2g__taxdetailpayableinvoiceexpense__c"},
    {"name": "c2g__taxdetailsalescreditnote__c"},
    {"name": "c2g__taxdetailsalesinvoice__c"},
    {"name": "c2g__transactionlog__c"},
    {"name": "c2g__transactionreconciliation__c"},
    {"name": "c2g__transactionreconciliationfilter__c"},
    {"name": "c2g__transactionreconciliationfilterstructure__c"},
    {"name": "c2g__transactionreconciliationlineitem__c"},
    {"name": "c2g__worker__c"},
    {"name": "c2g__workeritem__c"},
    {"name": "c2g__workerlog__c"},
    {"name": "c2g__workerloggroup__c"},
    {"name": "calc_building__c"},
    {"name": "calc_testing__c"},
    {"name": "calc_update__c"},
    {"name": "calculator_rate__c"},
    {"name": "calculator_update__c"},
    {"name": "call_merchant_notification__c"},
    {"name": "callcenter"},
    {"name": "campaign"},
    {"name": "campaignmember"},
    {"name": "campaignmemberstatus"},
    {"name": "case"},
    {"name": "casearticle"},
    {"name": "casecomment"},
    {"name": "casecontactrole"},
    {"name": "caseexternaldocument"},
    {"name": "casesolution"},
    {"name": "casestatus"},
    {"name": "casesubjectparticle"},
    {"name": "caseteammember"},
    {"name": "caseteamrole"},
    {"name": "caseteamtemplate"},
    {"name": "caseteamtemplatemember"},
    {"name": "caseteamtemplaterecord"},
    {"name": "cash_entry_bucket_s__c"},
    {"name": "cash_entry_wrapper__c"},
    {"name": "cashmatchingutilitiessettings__c"},
    {"name": "categorynode"},
    {"name": "categorynodelocalization"},
    {"name": "channelprogram"},
    {"name": "channelprogramlevel"},
    {"name": "channelprogrammember"},
    {"name": "chatter_group_access__c"},
    {"name": "chatteractivity"},
    # {"name": "chatterconversation"},
    # {"name": "chatterconversationmember"},
    {"name": "chatterextension"},
    {"name": "chatterextensionconfig"},
    {"name": "chatterextensionlocalization"},
    # {"name": "chattermessage"},
    {"name": "clicked_link__c"},
    # {"name": "clientbrowser"},
    {"name": "closer_cost__c"},
    {"name": "closer_performance_conversion_snapshot__c"},
    {"name": "closer_performance_submission_snapshot__c"},
    {"name": "closer_performance_transfers_snapshot__c"},
    {"name": "closer_quota__c"},
    {"name": "closer_speed_snapshot__c"},
    {"name": "clothing_apparel_snapshot__c"},
    {"name": "coa_statistics__c"},
    {"name": "coa_statistics_v2__c"},
    {"name": "coefficient__c"},
    {"name": "collaborationgroup"},
    {"name": "collaborationgroupmember"},
    {"name": "collaborationgroupmemberrequest"},
    {"name": "collaborationgrouprecord"},
    {"name": "collaborationinvitation"},
    {"name": "collection_issue_tracking__c"},
    {"name": "collection_issues_statistics__c"},
    {"name": "collection_schedule__c"},
    {"name": "collection_schedule_result__c"},
    {"name": "collections_cycle__c"},
    {"name": "collections_file__c"},
    {"name": "collections_issue__c"},
    {"name": "collections_issue__history", "last_modified_field": "createddate"},
    {"name": "collections_likelihood__c"},
    # {"name": "colordefinition"},
    {"name": "commission__c"},
    {"name": "community"},
    {"name": "connect_source_service__c"},
    # {"name": "connectedapplication"},
    {
        "name": "contact",
        "selectable": {
            "callable": lambda table, engine: Select(
                columns=[text("*")], from_obj=text(f'"sfoi"."{table}"')
            ).where(
                cast(column("systemmodstamp"), DATE) != cast(text("2018-07-16"), DATE)
            )
        },
    },
    {"name": "contactrequest"},
    {"name": "contentasset"},
    # {"name": "contentbody"},
    {"name": "contentdistribution"},
    {"name": "contentdistributionview"},
    {"name": "contentdocument"},
    # {"name": "contentdocumentlink"},
    {"name": "contentfolder"},
    # {"name": "contentfolderitem"},
    # {"name": "contentfoldermember"},
    # {"name": "contenthubitem"},
    {"name": "contenthubrepository"},
    # {"name": "contentnote"},
    {"name": "contentversion"},
    {"name": "continuous_variables__c"},
    {"name": "contract"},
    {"name": "contract__c"},
    {"name": "contract_block__c"},
    {"name": "contract_version_override__c"},
    {"name": "contractcontactrole"},
    {"name": "contractstatus"},
    {"name": "control_account_transaction_report__c"},
    {"name": "conversion_percent__c"},
    {"name": "corporate__c"},
    {"name": "cp_yodlee_bank_account__c"},
    {"name": "cron_trigger_ghost__c"},
    # {"name": "cronjobdetail"},
    # {"name": "crontrigger"},
    {"name": "cs_issues__c"},
    {"name": "css_test_customers__c"},
    {"name": "current_incompletes__c"},
    # {"name": "custombrand"},
    # {"name": "custombrandasset"},
    {"name": "customer__datacategoryselection"},
    {"name": "customer__ka"},
    {"name": "customer__kav"},
    # {"name": "customer__viewstat"},
    # {"name": "customer__votestat"},
    {"name": "customer_portal_activity__c"},
    {"name": "customer_portal_notification__c"},
    {"name": "customer_portal_popdown_configuration__c"},
    {"name": "customer_portal_popdown_notification__c"},
    {"name": "customer_service_issues__c"},
    {"name": "customhttpheader"},
    {"name": "customobjectuserlicensemetrics"},
    {"name": "custompermission"},
    {"name": "custompermissiondependency"},
    {"name": "daily__c"},
    {"name": "daily_incomplete_snapshot__c"},
    {"name": "daily_receipt_forecast_entry__c"},
    {"name": "daily_receipts_snapshot_2__c"},
    {"name": "daily_volume__c"},
    {"name": "dashboard"},
    {"name": "dashboard_receipts__c"},
    # {"name": "dashboardcomponent"},
    # {"name": "datacloudaddress"},
    {"name": "datacloudownedentity"},
    {"name": "datacloudpurchaseusage"},
    {"name": "dataintegrationrecordpurchasepermission"},
    {"name": "datasetexport"},
    # {"name": "datasetexportevent"},
    {"name": "datasetexportpart"},
    # {"name": "datastatistics"},
    # {"name": "datatype"},
    {"name": "day_entries_max_hrs__c"},
    {"name": "day_entry__c"},
    {"name": "dc_share_percentage__c"},
    {"name": "ddcassess__assessment_summary__c"},
    {"name": "ddcassess__entity_assessment__c"},
    {"name": "ddcassess__field_assessment__c"},
    {"name": "ddcassess__matched_record__c"},
    {"name": "declinedeventrelation"},
    {"name": "deduplication_rule__c"},
    {"name": "defaultvalue__c"},
    {"name": "defaultvalues__c"},
    {"name": "detail_account_transaction_report__c"},
    {"name": "dfss_snapshot_item__c"},
    {"name": "dfss_snapshot_push__c"},
    {"name": "directmessage"},
    # {"name": "directmessagemember"},
    {"name": "discount_call__c"},
    {"name": "discount_factor__c"},
    {"name": "discount_payout_snapshot__c"},
    {"name": "discountrate__c"},
    {"name": "document"},
    # {"name": "documentattachmentmap"},
    {"name": "documents_required_for_pricing__c"},
    {"name": "docusign_documents_required_templates__c"},
    {"name": "docusign_drf_field_mapping__c"},
    {"name": "docusign_field_mapping__c"},
    {"name": "docusign_settings__c"},
    {"name": "docusignmailer__c"},
    {"name": "domain"},
    {"name": "domainsite"},
    {"name": "drf_docusign_templates__c"},
    {"name": "drf_mkt_funnel_snapshot__c"},
    {"name": "drf_mkt_funnel_this_month_snapshot__c"},
    {"name": "drf_snapshot__c"},
    {"name": "drf_wos_to_converted_by_closr_snap_shot__c"},
    {"name": "ds_remote_service_config__c"},
    {"name": "dsfs__docusign_envelope__c"},
    {"name": "dsfs__docusign_envelope_document__c"},
    {"name": "dsfs__docusign_envelope_recipient__c"},
    {"name": "dsfs__docusign_recipient_status__c"},
    {"name": "dsfs__docusign_status__c"},
    {"name": "dsfs__docusignaccountconfiguration__c"},
    {"name": "duplicate_leadtoaccount_buffer__c"},
    {"name": "duplicate_phone_buffer__c"},
    {"name": "duplicated_item__c"},
    {"name": "duplicatejob"},
    {"name": "duplicatejobdefinition"},
    {"name": "duplicatejobmatchingrule"},
    {"name": "duplicatejobmatchingruledefinition"},
    {"name": "duplicaterecorditem"},
    {"name": "duplicaterecordset"},
    {"name": "duplicaterule"},
    {"name": "ecommercemember__c"},
    {"name": "eft_file_number__c"},
    {"name": "email_alert__c"},
    {"name": "email_alert_tracking__c"},
    {"name": "email_template_access__c"},
    {"name": "email_template_tracking__c"},
    {"name": "emailmessage"},
    {"name": "emailmessagerelation"},
    {"name": "emailservicesaddress"},
    {"name": "emailservicesfunction"},
    # {"name": "emailstatus"},
    {"name": "emailtemplate"},
    # {"name": "embeddedservicedetail"},
    {"name": "employee_rating__c"},
    # {"name": "entitydefinition"},
    # {"name": "entityparticle"},
    # {"name": "entitysubscription"},
    {"name": "equifaxquery__c"},
    {"name": "equifaxtrade__c"},
    {"name": "error_log__c"},
    {"name": "event"},
    # {"name": "eventbussubscriber"},
    {"name": "eventlogfile"},
    {"name": "eventrelation"},
    {"name": "evo_payment__c"},
    {"name": "exchange_rate__c"},
    {"name": "expected_vs_actual_receipt__c"},
    {"name": "external_api_credential__c"},
    {"name": "externaldatasource"},
    {"name": "externaldatauserauth"},
    {"name": "externalsocialaccount"},
    {"name": "fairwarn__alert__c"},
    {"name": "fairwarn__alertticketassociation__c"},
    {"name": "fairwarn__investigation__c"},
    {"name": "fairwarn__involved_user__c"},
    {"name": "features__c"},
    {"name": "feedcomment"},
    # {"name": "feedlike"},
    # {"name": "feedsignal"},
    # {"name": "feedtrackedchange"},
    {"name": "ff_summary__c"},
    {"name": "ffbext__onetouchsettings__c"},
    {"name": "ffpayup__codatemporalpaymentlineitem__c"},
    {"name": "ffpayup__codaupgradeerror__c"},
    {"name": "field_reference__c"},
    {"name": "field_trip__field_analysis__c"},
    {"name": "field_trip__object_analysis__c"},
    # {"name": "fielddefinition"},
    {"name": "fieldpermissions"},
    {"name": "file_log__c"},
    {"name": "file_storage__c"},
    {"name": "filesearchactivity"},
    {"name": "financial_institution__c"},
    {"name": "financial_sales_tool__c"},
    {"name": "fiscalyearsettings"},
    {"name": "fixed_cost_statistics__c"},
    {"name": "flag_as_corporate__c"},
    # {"name": "flexqueueitem"},
    {"name": "flowinterview"},
    {"name": "flowstagerelation"},
    {"name": "folder"},
    # {"name": "folderedcontentdocument"},
    {"name": "frictionless_score_mca_grad__c"},
    {"name": "frictionless_score_mca_reg__c"},
    {"name": "frictionless_score_monthly_snapshot__c"},
    {"name": "funding__c"},
    {"name": "funding_calculation_sheet__c"},
    {"name": "funding_forecast__c"},
    {"name": "funding_quarter_statistics__c"},
    {"name": "g_settings__c"},
    {"name": "galland_query_field__c"},
    {"name": "galland_score_statistics__c"},
    {"name": "generic_dsm_d_casl_1__c"},
    {"name": "generic_dsm_d_casl_2__c"},
    {"name": "gift_card__c"},
    {"name": "good_underwriting_days_snapshot__c"},
    {"name": "google_adwords_statistics__c"},
    {"name": "google_doc_mapping__c"},
    {"name": "graduated_advance_analyt__c"},
    {"name": "graduated_advance_speed_snapshot__c"},
    {"name": "grantedbylicense"},
    {"name": "group"},
    {"name": "groupmember"},
    {"name": "growthpayout__c"},
    {"name": "hair_and_beauty_snapshot__c"},
    {"name": "helpdesk__c"},
    {"name": "holiday"},
    {"name": "icalendar__icalendaroptions__c"},
    # {"name": "icondefinition"},
    {"name": "icrt__guide_attributes_translation__c"},
    {"name": "icrt__guide_definition__c"},
    {"name": "icrt__guide_execution__c"},
    {"name": "icrt__guide_milestone__c"},
    {"name": "idea"},
    # {"name": "ideacomment"},
    {"name": "ideassitesetup__c"},
    {"name": "impact_radius_notification__c"},
    {"name": "import__c"},
    {"name": "inbound_email__c"},
    {"name": "incomescheduleutilitiessettings__c"},
    {"name": "incomplete_responsible__c"},
    {"name": "incompletes_to_funding_ratio__c"},
    {"name": "individual"},
    {"name": "industry_areacode_statistics__c"},
    {"name": "industry_cluster_pd__c"},
    {"name": "industry_cluster_tc__c"},
    {"name": "industry_macro_data__c"},
    {"name": "industry_macro_data_value__c"},
    {"name": "inf_snapshot__c"},
    {"name": "informatica_endpoints__c"},
    {"name": "installedmobileapp"},
    {"name": "intercom99__intercomapisettings__c"},
    {"name": "internal_ip_address__c"},
    {"name": "interview__c"},
    {"name": "intuit_referral_reporting__c"},
    {"name": "issue__c"},
    {"name": "job_posting__c"},
    {"name": "journal_wrapper__c"},
    {"name": "key_collections_issues_over_20k_shapshot__c"},
    {"name": "key_collections_issues_snapshot__c"},
    {"name": "key_performance_indicator__c"},
    {"name": "knowledgeableuser"},
    {"name": "knowledgearticle"},
    {"name": "knowledgearticleversion"},
    # {"name": "knowledgearticleviewstat"},
    # {"name": "knowledgearticlevotestat"},
    {"name": "landlord_fee_structure__c"},
    {"name": "latest_created_opp_snapshot__c"},
    {"name": "lead"},
    {"name": "lead_assignment_industry_priority__c"},
    {"name": "lead_assignment_priority__c"},
    {"name": "lead_assignment_rule__c"},
    {"name": "lead_assignment_rule_user__c"},
    {"name": "lead_conversion_factor__c"},
    {"name": "lead_cost__c"},
    {"name": "lead_gen_quota__c"},
    {"name": "lead_source__c"},
    {"name": "leadactivitywrap__c"},
    {"name": "leadassignmentsettings__c"},
    {"name": "leadlinker__c"},
    {"name": "leadstatus"},
    {"name": "lessons_learned__c"},
    {"name": "lgd__c"},
    {"name": "lightningexperiencetheme"},
    {"name": "lightningtogglemetrics"},
    {"name": "lightningusagebyapptypemetrics"},
    {"name": "lightningusagebybrowsermetrics"},
    {"name": "lightningusagebyflexipagemetrics"},
    {"name": "lightningusagebypagemetrics"},
    {"name": "lineitemoverride"},
    {"name": "linkedarticle"},
    {"name": "listemail"},
    {"name": "listemailrecipientsource"},
    {"name": "listview"},
    {"name": "listviewchart"},
    # {"name": "listviewchartinstance"},
    {"name": "loan_maturity_component__c"},
    {"name": "loan_multiplier__c"},
    {"name": "loans_contracts_in_and_out_snapshot__c"},
    {"name": "location__c"},
    {"name": "login_stage__c"},
    {"name": "login_to_portal_url__c"},
    # {"name": "loginevent"},
    # {"name": "logineventstream"},
    # {"name": "loginip"},
    # {"name": "logouteventstream"},
    # {"name": "lookedupfromactivity"},
    {"name": "lstore__document_view__c"},
    {"name": "lstore__storage_settings__c"},
    {"name": "lstore__stored_document__c"},
    {"name": "macro"},
    {"name": "macroinstruction"},
    {"name": "mailmergetemplate"},
    {"name": "marketing_auto_fields__c"},
    {"name": "marketing_beauty__c"},
    {"name": "marketing_restaurant_fields__c"},
    {"name": "mass_email__c"},
    {"name": "mass_email_message__c"},
    {"name": "mass_email_recipient__c"},
    {"name": "mass_email_stats__c"},
    {"name": "matchingrule"},
    {"name": "matchingruleitem"},
    {"name": "maximum_available_discount_range__c"},
    {"name": "maximum_funding_model_output__c"},
    {"name": "mca_whp_rates__c"},
    {"name": "merchant_history__c"},
    {"name": "merchant_information_update__c"},
    {"name": "merchant_lead__c"},
    {"name": "merchant_milestone__c"},
    {"name": "mercy_requests__c"},
    {"name": "merge_pricings__c"},
    {"name": "merge_pricings_v2__c"},
    {"name": "milestone__c"},
    {"name": "missed_deposit_advance_size_comparison__c"},
    {"name": "monday_receipts_snapshot__c"},
    {"name": "moneris_monthly_volumes__c"},
    {"name": "monerismultilocationotification__c"},
    {"name": "monthly_approval_entry__c"},
    {"name": "monthly_volume_archive__c"},
    {"name": "myobj__c"},
    # {"name": "name"},
    {"name": "namedcredential"},
    {"name": "namespaceregistry"},
    {"name": "navigationlinkset"},
    {"name": "navigationmenuitem"},
    {"name": "navigationmenuitemlocalization"},
    {"name": "network"},
    {"name": "networkaffinity"},
    {"name": "networkmember"},
    {"name": "networkmembergroup"},
    {"name": "networkpageoverride"},
    {"name": "networkselfregistration"},
    {"name": "new_dashboard_receipt__c"},
    {"name": "new_pricing_created__c"},
    {"name": "not_now_in_future_mkt_funnel_snapshot__c"},
    {"name": "note"},
    {"name": "notificationactivity__c"},
    {"name": "nsf_weekly_collection_snapshot__c"},
    {"name": "nsfs__c"},
    {"name": "nubik_salesvalue__c"},
    # {"name": "oauthtoken"},
    {"name": "objectpermissions"},
    {"name": "off_balance_sheet_financing__c"},
    {"name": "one_penny__c"},
    {"name": "one_penny_cash_entry__c"},
    {"name": "open_cases__c"},
    # {"name": "openactivity"},
    {"name": "opportunity", "selectable": {"callable": format_wide_table_select}},
    {"name": "opportunityhistory"},
    {"name": "opportunity_sales_note__c"},
    {"name": "opportunity_statistic__c"},
    {"name": "opportunitycompetitor"},
    {"name": "opportunitycontactrole"},
    {"name": "opportunitylineitem"},
    {"name": "opportunitylineitemschedule"},
    {"name": "opportunityoverride"},
    {"name": "opportunitypartner"},
    {"name": "opportunitystage"},
    # {"name": "organization"},
    # {"name": "orglifecyclenotification"},
    {"name": "orgwideemailaddress"},
    # {"name": "outgoingemail"},
    # {"name": "outgoingemailrelation"},
    # {"name": "ownedcontentdocument"},
    # {"name": "ownerchangeoptioninfo"},
    {"name": "packagelicense"},
    {"name": "parent__c"},
    {"name": "partner"},
    {"name": "partner_referral__c"},
    {"name": "partner_settings__c"},
    {"name": "partnerrole"},
    {"name": "partners__c"},
    {"name": "payment_schedule__c"},
    {"name": "paymentech_notification_emails__c"},
    {"name": "pd_output__c"},
    {"name": "pending_chatter__c"},
    {"name": "pending_mfmo_account__c"},
    {"name": "pending_wyman_opportunity__c"},
    {"name": "pendingworkentry__c"},
    {"name": "percent_of_max_advance_size__c"},
    {"name": "period"},
    # {"name": "permissionset"},
    # {"name": "permissionsetassignment"},
    {"name": "permissionsetlicense"},
    {"name": "permissionsetlicenseassign"},
    {"name": "phone_number_buffer__c"},
    {"name": "picklist_fields__c"},
    {"name": "picklist_options__c"},
    # {"name": "picklistvalueinfo"},
    {"name": "pipeline_stage_by_rep__c"},
    {"name": "pipeline_trend__c"},
    # {"name": "platformaction"},
    {"name": "platformcachepartition"},
    {"name": "platformcachepartitiontype"},
    {"name": "pmsp_snapshot__c"},
    {"name": "portal_application_activity__c"},
    {"name": "portal_logins_snapshot__c"},
    {"name": "portfolio_growth_snapshot__c"},
    {"name": "portfolio_size__c"},
    {"name": "portfolio_speed_snapshot_125k__c"},
    {"name": "portfolio_speed_snapshot_50k__c"},
    {"name": "portfolio_speed_snapshot__c"},
    {"name": "portfolio_speed_snapshot_high_risk_pric__c"},
    {"name": "portfolio_speed_snapshot_pmq__c"},
    {"name": "post_funding_call_new__c"},
    {"name": "post_may_2013_targets__c"},
    {"name": "potential_duplicated_lead__c"},
    {"name": "pre_underwriting_checklist__c"},
    {"name": "prepaid_credit_card_information__c"},
    {"name": "press__c"},
    {"name": "pricebook2"},
    {"name": "pricebookentry"},
    {"name": "pricing__c", "selectable": {"callable": format_wide_table_select}},
    {"name": "pricingsupplementary__c"},
    {"name": "pricing_category__c"},
    {"name": "pricing_details__c"},
    {"name": "pricing_document_type__c"},
    {"name": "pricing_documentation_required__c"},
    {"name": "pricing_documents_for_upload__c"},
    {"name": "pricing_oppen__c"},
    {"name": "pricing_option__c"},
    {"name": "pricing_product__c"},
    {"name": "pricing_product_product_category__c"},
    {"name": "pricing_rejection_criteria__c"},
    {"name": "pricing_snapshot__c"},
    {"name": "pricing_source__c"},
    {"name": "priority_5_snapshot__c"},
    {"name": "priority_7_snapshot__c"},
    {"name": "priority_tracking__c"},
    {"name": "probability_of_default__c"},
    {"name": "processdefinition"},
    {"name": "processinstance"},
    {"name": "processinstancenode"},
    {"name": "processinstancestep"},
    {"name": "processinstanceworkitem"},
    {"name": "processnode"},
    {"name": "processor__c"},
    {"name": "product2"},
    {"name": "profile"},
    {"name": "profitability__c"},
    {"name": "project__c"},
    {"name": "project_charter__c"},
    {"name": "project_constraints__c"},
    {"name": "project_requirement__c"},
    {"name": "promo_code__c"},
    {"name": "promo_code_applied__c"},
    {"name": "proposal_mkt_funnel_snapshot__c"},
    {"name": "provisions_snapshot__c"},
    # {"name": "publisher"},
    {"name": "push_funding_schedule__c"},
    {"name": "push_funding_schedule_account__c"},
    {"name": "push_funding_statistic__c"},
    {"name": "push_funding_summary__c"},
    {"name": "pushtopic"},
    {"name": "quality_assurance__c"},
    {"name": "quantityforecast"},
    {"name": "query_field__c"},
    {"name": "question"},
    {"name": "questiondatacategoryselection"},
    {"name": "queuesobject"},
    {"name": "quicktext"},
    {"name": "ratingimageurl__c"},
    # {"name": "recentlyviewed"},
    {"name": "record_assignment__c"},
    {"name": "record_pool__c"},
    {"name": "recordaction"},
    {"name": "recordtype"},
    {"name": "recordtypelocalization"},
    {"name": "red_flag_tracking__c"},
    {"name": "referral_offer__c"},
    {"name": "region__c"},
    {"name": "relationship__c"},
    # {"name": "relationshipdomain"},
    # {"name": "relationshipinfo"},
    {"name": "repeat_eligible_projected_snapshot__c"},
    {"name": "repeat_sop_factor__c"},
    {"name": "repeat_target__c"},
    {"name": "reply"},
    {"name": "report"},
    {"name": "reported_error_object__c"},
    # {"name": "reportevent"},
    # {"name": "reporteventstream"},
    {"name": "reputationlevel"},
    {"name": "reputationlevellocalization"},
    {"name": "reputationpointsrule"},
    {"name": "request__c"},
    {"name": "requested_advance_size_by_rep__c"},
    {"name": "reseller_group__c"},
    {"name": "reserve_balance__c"},
    {"name": "reserved_lead_to_assign__c"},
    {"name": "restaurant_snapshot__c"},
    {"name": "revenueforecast"},
    {"name": "review__c"},
    {"name": "risk_model_output__c"},
    {"name": "risk_profit_class_snapshot__c"},
    {"name": "risk_score__c"},
    {"name": "roi_statistics__c"},
    {"name": "rypple_corp__badge__c"},
    {"name": "sales_budget_day__c"},
    {"name": "sales_budget_month__c"},
    {"name": "sales_metrics__c"},
    {"name": "sales_monthly_performance__c"},
    {"name": "sales_note__c"},
    {"name": "sales_tracking__c"},
    {"name": "samlssoconfig"},
    {"name": "scontrol"},
    {"name": "scontrollocalization"},
    {"name": "scoring_gap__c"},
    {"name": "scratchorginfo"},
    {"name": "searchactivity"},
    # {"name": "searchlayout"},
    {"name": "searchpromotionrule"},
    {"name": "seasonality__c"},
    {"name": "secure_files__c"},
    {"name": "secure_notes__c"},
    {"name": "secureagentscluster"},
    {"name": "selfserviceuser"},
    {"name": "sessionpermsetactivation"},
    # {"name": "setupaudittrail"},
    {"name": "setupentityaccess"},
    {"name": "sfdc_url__c"},
    {"name": "share_article__c"},
    {"name": "share_of_profit__c"},
    # {"name": "site"},
    {"name": "site_visit__c"},
    # {"name": "sitedetail"},
    {"name": "sitesnames__c"},
    {"name": "sobjecttransferbatchemails__c"},
    {"name": "socialpersona"},
    {"name": "socialpost"},
    {"name": "solution"},
    {"name": "solutionstatus"},
    {"name": "sop_bi_weekly__c"},
    {"name": "sop_calc__c"},
    {"name": "sop_multiples__c"},
    {"name": "sop_target__c"},
    {"name": "specified_amount_os__c"},
    {"name": "sprint_burn_down_snapshot__c"},
    {"name": "sql_updates__c"},
    {"name": "squaresettings__c"},
    {"name": "stage_time_entry__c"},
    {"name": "stamp"},
    {"name": "stampassignment"},
    {"name": "stamplocalization"},
    {"name": "statements_perfomance_entry__c"},
    {"name": "staticresource"},
    {"name": "streamingchannel"},
    {"name": "supplier_contract__c"},
    {"name": "survey__c"},
    {"name": "sync_queue__c"},
    {"name": "system_settings__c"},
    # {"name": "tabdefinition"},
    {"name": "tagdefinition"},
    {"name": "task"},
    {"name": "taskpriority"},
    {"name": "taskstatus"},
    {"name": "tc_app_areacode__c"},
    {"name": "td_notification_emails__c"},
    {"name": "tech_services_statistics__c"},
    {"name": "tenantusageentitlement"},
    {"name": "testsuitemembership"},
    {"name": "thierno_test__c"},
    # {"name": "thirdpartyaccountlink"},
    {"name": "time_in_business__c"},
    {"name": "time_in_collection_percent__c"},
    {"name": "todaygoal"},
    {"name": "top_up_component__c"},
    {"name": "top_up_snapshot__c"},
    {"name": "topic"},
    {"name": "topicassignment"},
    {"name": "topiclocalization"},
    {"name": "topupandsmallamountratios__c"},
    {"name": "total_funding__c"},
    {"name": "total_fundings_snapshot__c"},
    {"name": "total_portfolio_mca_loan__c"},
    {"name": "trac_emailnotificationconfig__c"},
    {"name": "trac_intuitconfig__c"},
    {"name": "trac_leadapplicationconfig__c"},
    {"name": "training_c__c"},
    {"name": "training_sessions__c"},
    {"name": "transaction_pool__c"},
    # {"name": "transactionsecuritypolicy"},
    {"name": "transfer__c"},
    {"name": "transfer_assignment_buckets__c"},
    {"name": "transfer_to_conversions__c"},
    {"name": "transformation_parameters__c"},
    {"name": "undecidedeventrelation"},
    {"name": "unsubscribe_request__c"},
    {"name": "url_rewrite__c"},
    {"name": "url_rewriter_diff__c"},
    {"name": "user"},
    {"name": "user_management__c"},
    {"name": "user_permission__c"},
    {"name": "user_permission_values__c"},
    {"name": "user_user_permission__c"},
    {"name": "useraccountteammember"},
    {"name": "userappinfo"},
    {"name": "userappmenucustomization"},
    # {"name": "userappmenuitem"},
    {"name": "usercustombadge"},
    {"name": "usercustombadgelocalization"},
    # {"name": "userentityaccess"},
    # {"name": "userfieldaccess"},
    {"name": "userlicense"},
    {"name": "userlistview"},
    {"name": "userlistviewcriterion"},
    # {"name": "userlogin"},
    {"name": "userpackagelicense"},
    # {"name": "userpermissionaccess"},
    {"name": "userpreference"},
    {"name": "userprovisioningrequest"},
    # {"name": "userrecordaccess"},
    {"name": "userrole"},
    {"name": "utm_parameters__c"},
    {"name": "vaibtest__c"},
    {"name": "variability_statistics__c"},
    # {"name": "visibilitychangenotification"},
    {"name": "volumes_weight_for_funding_benchmark__c"},
    # {"name": "vote"},
    {"name": "w_wyman_settings__c"},
    {"name": "watch_item__c"},
    {"name": "waveautoinstallrequest"},
    {"name": "wavecompatibilitycheckitem"},
    {"name": "web_lead_source__c"},
    {"name": "website_generic__c"},
    {"name": "website_privacy_policy__c"},
    {"name": "weekly_bonus__c"},
    {"name": "weekly_status_report__c"},
    {"name": "welcome_call__c"},
    {"name": "welcome_letter_generation__c"},
    {"name": "win_percentage_factor__c"},
    {"name": "wip_entry__c"},
    {"name": "withdrawal__c"},
    {"name": "workaccess"},
    {"name": "workaround_cash_entry_lines__c"},
    {"name": "workbadge"},
    {"name": "workbadgedefinition"},
    {"name": "working_days__c"},
    {"name": "working_month__c"},
    {"name": "workthanks"},
    {"name": "writeoff__c"},
    {"name": "wyman_manual_inputs__c"},
    {"name": "x90_day_conversions_snapshot__c"},
    {"name": "yodlee_account__c"},
    {"name": "yodlee_merchants_snapshot__c"},
    {"name": "yodlee_status__c"},
    {"name": "zero_report_snapshot__c"},
]
